### PR TITLE
README: There are multiple Flatpaks available

### PR DESCRIPTION
**Pull request by USA-RedDragon**
It looks like nmlynch94 and I started working on Flatpaks around the same time. We take two completely different approaches for these Flatpaks and more options are always better for the FOSS community in the event one should become unmaintained.

Some of the ways my Flatpak is different:

#### Wine

The `nmlynch94` launcher [uses](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/blob/6e1b5bf4c78b707bcb15d6f85d8b48e0337b7525/com.jagex.Launcher.yml#L21-L23) the [unoffical Flatpak Wine](https://github.com/flathub/org.winehq.Wine) package. This package is not maintained by the Wine project and is several versions behind. This has several effects:

- This unofficial Wine package is missing many of the improvements that have been made to Wine recently.
- Because the unofficial Wine Flatpak is meant to be a one-size-fits-all installation of Wine, the size of the Flatpak is much larger than it needs to be, because it includes many dependencies that are not needed by the Jagex Launcher and it's games.
- The permissions required for the unofficial Wine are larger because it requests access to the host filesystem along with accessing devices. This is not needed by the Jagex Launcher and it's games, so these permissions expand the attack surface of the Flatpak without providing any benefit.

`nmlynch94`'s Flatpak also [contains a prebuilt Proton GE](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/blob/35b90122cffb994bf506d0d36939bdb14c308973/com.jagex.Launcher.yml#L55-L65) which makes the Wine base even more unnecessary and illogical.

#### DXVK

The Jagex Launcher, Runescape's NXT client, the official OSRS client, and RuneLite all use OpenGL. (The exception is running NXT with compatibility mode) The `nmlynch94` launcher [adds DXVK](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/blob/35b90122cffb994bf506d0d36939bdb14c308973/com.jagex.Launcher.yml#L99-L108), which just adds overhead and goes unused.

#### Custom Clients

The `nmlynch94` launcher contains support for other clients such as HDOS. If these clients are important to you, you should use the `nmlynch94` launcher. However, if you only care about the official Jagex client and RuneLite, my launcher is a better option.

#### Coherent Commit Messages

The `nmlynch94` launcher's [commit history](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/commits/35b90122cffb994bf506d0d36939bdb14c308973) is littered with commit messages like "Update <filename>" and "test", so understanding the changes that were made to the repo is difficult.

#### Continuous Integration

My Flatpak also uses [GitHub Actions](https://github.com/features/actions) to test changes and ensure the Flatpak builds successfully. This means that the Flatpak will always be tested before being released and allows the next benefit: automatic dependency updates.

#### Automatic Dependency Updates

My Flatpak repository uses [Renovate](https://www.mend.io/renovate/) to create automated pull requests to update dependencies. This means that the dependencies will be kept up to date without any manual intervention. This ensures that users will always have the latest versions of Wine and Runelite. `nmlynch94` does not use CI or Renovate, so the dependency update process is manual.

#### Copyrighted Content

My Flatpak repository contains zero content that is the intellectual property of Jagex which allows it to be open sourced under a very permissive license. The `nmlynch94` launcher [contains the Jagex launcher logo](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/blob/6e1b5bf4c78b707bcb15d6f85d8b48e0337b7525/icons/512/512.png) that belongs to Jagex.

The lack of a license on the `nmlynch94` repository means that it is not legal to distribute or modify `nmlynch94`'s launcher package and that it is proprietary.

### CODE REVIEW

**Comment by nmlynch94** [comment]
Hello! Thanks for the PR. I'm new to building flatpaks so have been hacking around a bit as you can tell haha. All of the deficiencies you mentioned are things I was planning to figure out but, seeing as you already have, we could just add HDOS into this project and then recommend that if you aren't against that. Once it has HDOS, my repo has no advantages over yours, seeing as they both rely on the installation script from this repo.

Am planning to test it to make sure it functions on the steam deck properly. I'm aware DXVK is unnecessary overhead, but in Game Mode on the deck I was getting a DLL load error for dxgi.dll. It worked fine in Desktop mode as well as on all my test machines, but failed in Game Mode. The only way I could get it working was by adding in dxvk, because otherwise it failed to find the default dxgi.dll and crashed (an idea from the people in the GE Discord). Curious to see if yours suffers from the same issue. 

All that being said, I'm currently unable to get this running on my machine. 

```
nate@fedora:~/Downloads$ flatpak remote-add --if-not-exists JagexLauncher https://jagexlauncher.flatpak.mcswain.dev/.flatpakrepo
flatpak install --user JagexLauncher com.jagex.Launcher
error: Can't load uri https://jagexlauncher.flatpak.mcswain.dev/.flatpakrepo: Server returned status 404

Looking for matches…
error: No remote refs found for ‘JagexLauncher’
```

When I try to run it manually, I get an ffmpeg error:
```
nate@fedora:~/com.jagexlauncher.JagexLauncher$ flatpak run com.jagex.Launcher
bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system
error: ldconfig failed, exit status 256
nate@fedora:~/com.jagexlauncher.JagexLau
```

I think I have all the dependencies installed, so not sure what is missing.

**Comment by USA-RedDragon** [comment]
> we could just add HDOS into this project and then recommend that if you aren't against that

Definitely not against that, just curious how this would be launched while still supporting RuneLite since the Jagex launcher runs `RuneLite.exe`. Another `.desktop` file for HDOS maybe?

> Lastly, I don't think your final point about expanded permissions on the base flatpak applies here, does it? I'm pretty sure the finish-args from the base don't override the application inheriting it. My flatpak does not have all the filesystem permissions from the base wine flatpak, for example.

Yeah fair... I'm somewhat new to Flatpaks too, so I might have misunderstood this. My thinking was that it does inherit, but I couldn't find a proper reference for this on the Flatpack docs. 

> All that being said, I'm currently unable to get this running on my machine. Looks like the remote in the README is incorrect.

Whoops, looks like GitHub pages ate my (`.flatpakrepo`) homework. 

> Am planning to test it to make sure it functions on the steam deck properly. I'm aware DXVK is unnecessary overhead, but in Game Mode on the deck I was getting a DLL load error for dxgi.dll. It worked fine in Desktop mode as well as on all my test machines, but failed in Game Mode

Interesting find. My Deck is currently on a shelf dead, so collaborating to figure this out for sure would be helpful.

Let me clear out my flatpak installation and I'll have a look at that FFmpeg issue, I think I have an inkling about it

**Comment by nmlynch94** [comment]
In case it helps, I ran into an issue where doing a single-file-bundle installation completely ignored extensions needed from flathub so I had to include a script that installed them manually. Seems like a long-standing bug and distributing with bundles is not a high-priority feature it seems. I made sure I have the ffmpeg extensions, but it could be that I’m missing something else. May be solved now that your remote is fixed so I’ll give that a go in a bit.

**Comment by USA-RedDragon** [comment]
> Seems like a long-standing bug and distributing with bundles is not a high-priority feature it seems

That rings a bell. I'm in favor of not even supporting those since I doubt many folks are hell-bent on single file bundles. I would think since `.flatpakref` files exist that can automatically add a repo and the relevant app, this packaging form is probably more of an edge-case than a standard distribution method.

**Comment by nmlynch94** [comment]
Yeah, I agree. Anyone who would want a bundle can just use flatpak-builder. Not like a bundle even supports offline installation due to the dependency problem lol.

Fwiw, still getting the ffmpeg error when downloading from the repo. The repo adding and installation itself is working now, though.

For HDOS, you can do the same method as RuneLite where you add the jar as an exe file and then update the registry:
- Jar file: https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/blob/main/com.jagex.Launcher.yml#L84
- Reg entry: https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/blob/main/scripts/jagex-run.sh#L16

Then it'll have a functional play button in the launcher.

**Comment by USA-RedDragon** [comment]
> Fwiw, still getting the ffmpeg error when downloading from the repo. The repo adding and installation itself is working now, though.

Yeah, I've got a build going, just takes a lil bit to recompile Wine.

> Then it'll have a functional play button in the launcher.

Ahh so the Jagex Launcher will offer HDOS as an option if it's installed? That'd make sense.

**Comment by USA-RedDragon** [comment]
I could be wrong, but unless Pulse or GStreamer (not sure which the different clients use) use `ffmpeg` codecs, we might not actually need those.

**Comment by nmlynch94** [comment]
Also, any reason you disable the flatpak sandbox when you launch the application?

**Comment by USA-RedDragon** [comment]
Nvidia... I can't get GL working without it on my host

**Comment by nmlynch94** [comment]
Hmm yeah I think the Jagex Launcher itself uses CEF. When I helped AdamCake with the Bolt-Launcher flatpak, we had to add some patches to get it working, however, I've never had to do that for the Jagex Launcher. It worked in my and the Lutris flatpak without it, so not sure why might be missing. My host uses a Nvidia GPU as well.

**Comment by USA-RedDragon** [comment]
Well I just tried it without the `--no-sandbox` and `--no-gpu-sandbox` and I still got into the launcher, so maybe I fixed that somewhere along the way :shrug: 

Very possible I was using that before I realized my user and system flatpak installs differed

**Comment by USA-RedDragon** [comment]
HDOS wants to start but this first load seems suspiciously slow

**Comment by USA-RedDragon** [comment]
Never mind, I'm just too impatient on the first launch apparently. It worked quite fast the second launch.

image
image

**Comment by USA-RedDragon** [comment]
Sound worked in HDOS (I forgot how much I miss the classic login music :heart_eyes:) and RS3. I broke the RuneLite launcher trying to tidy it a bit, so I'll check that and push to the repo in a few

**Comment by nmlynch94** [comment]
Awesome! I think it also may not save settings between flatpak restarts for RuneLite as it stands right now. You’ll probably have to add jvm args to store it in XDG_DATA_HOME. Mine does that if you want an example.

**Comment by USA-RedDragon** [comment]
> I think it also may not save settings between flatpak restarts for RuneLite

Yeah that was my next thing to check out. I wasn't sure where it tried to save. Thanks for pointing it out

**Comment by USA-RedDragon** [comment]
And that's RuneLite with sound

image

I just pushed the flatpak repo with the ffmpeg stuff removed. Haven't done the `XDG_DATA_HOME` stuff yet.

**Comment by Adamcake** [comment]
Runelite not saving settings is due to its sandbox not having access to the `~/.runelite` directory. The traditional way to fix that is by overriding the JVM's `user.home` property to a path inside the sandbox. But, as long as you're not intending for this to ever work anywhere other than flatpak, you could take the easier option and add `--persist=.runelite` as a finish arg. That way you won't have to mess around with any XDG or JVM stuff.

> The --persist=path option can be used to map paths from the user's home directory into the sandbox filesystem. This makes it possible to avoid configuring access to the entire home directory, and can be useful for applications that hardcode file paths in ~/ .

**Comment by USA-RedDragon** [comment]
Latest repo push adds in `~/.runelite` and `~/hdos` persistence.

**Comment by USA-RedDragon** [comment]
I had to use the `-Duser.home` trick in `_JAVA_OPTIONS` for HDOS because `strace` + experimentation shows it likes saving files at the root of the home directory (particularly the app preferences), and since it runs Java as a subprocess the environment variable was the only solution I found. It seems Runelite has an option for it, but the same option doesn't work in HDOS. But I worked around it and HDOS preferences save.

Now to battle test it. I think I've got an AMD card somewhere to test it with `mesa`. I'll pop a liveusb in my laptop to test on Intel graphics. I am particularly curious about cutscenes, since it's possible those might use those `ffmpeg` libs I ripped out.

As far as the DXVK and Steam Deck thing, if the error does pop up again, I wonder if there's not something like a `DLLOVERRIDE` environment variable forcing DXVK on. I _think_ if that's the case we can hardcode it in the launcher script to use the Wine library and it should work.

**Comment by nmlynch94** [comment]
1. Same issue is at play on the steam deck. However, I inspected the env vars and it's setting dxgi=native in Gaming Mode, which would explain our issue. Exporting WINEDLLOVERRIDES=dxgi=b allows it to launch in gaming mode. 

2. I cannot type on the launcher when it opens. A dependency is probably missing, but I encountered this problem originally which I solved by using wine-ge.

**Comment by nmlynch94** [comment]
I also cannot launch the flatpak on my machine, only on the steam deck. Don't have time to troubleshoot ATM but here is the error:

```
01cc:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 5, 005F2620, 16): stub
01cc:fixme:process:validate_proc_thread_attribute Unhandled attribute 26
01cc:fixme:process:CreateProcessInternalW Unsupported attribute 0x2000e.
01cc:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenAppContainerSid, ...) semi-stub
[1128/173244.985:FATAL:gpu_data_manager_impl_private.cc(451)] GPU process isn't usable. Goodbye.
wine: Unhandled exception 0x80000003 in thread 17c at address 75897EAD (thread 017c), starting debugger...
Can't attach process 0178: error 5
➜  ~ 
➜  ~ curl -fSsL https://raw.githubusercontent.com/USA-RedDragon/jagex-launcher-flatpak/main/install.sh | bash
Skipping: org.freedesktop.Platform/x86_64/23.08 is already installed
Skipping: org.freedesktop.Platform.Compat.i386/x86_64/23.08 is already installed
Skipping: org.freedesktop.Platform.GL32.default/x86_64/23.08 is already installed
Skipping: org.freedesktop.Platform.GL.nvidia-535-129-03/x86_64/1.4 is already installed
Skipping: org.freedesktop.Platform.GL32.nvidia-535-129-03/x86_64/1.4 is already installed
```

**Comment by TormStorm** [comment]
Hello, i have been looking through your Flatpak and everything looks good, but when i tried testing it on my laptop i'm running into some issues. Here is my hardware information:

Host: 20N20076MX ThinkPad T490 
Kernel: 6.6.2-201.fsync.fc38.x86_64 
Uptime: 1 hour, 28 mins 
Packages: 2657 (rpm), 64 (flatpak) 
Shell: bash 5.2.15 
Resolution: 1920x1080 
DE: Plasma 5.27.9 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: Intel i5-8265U (8) @ 3.900GHz 
GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
Memory: 2792MiB / 23686MiB 


Wayland:
Under Wayland i get this error when i try to run it from the terminal:
` [torm@torm-pc2 ~]$ 01d0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
01d0:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."`

X11
I get a little further under X11, the wine configurations starts, but crashes after a few seconds:
wine_crash

Here is the full log under Wayland:
[Log_Wayland.txt](https://github.com/TormStorm/jagex-launcher-linux/files/13494324/Log_Wayland.txt)

And here is the full log under X11:
[log_X11.txt](https://github.com/TormStorm/jagex-launcher-linux/files/13494326/log_X11.txt)

**Comment by USA-RedDragon** [comment]
Can confirm the Wayland issue, think I have a fix. I was misusing YAML merge keys for lists of config options, one of them being `--with-wayland`. 

I think https://github.com/USA-RedDragon/jagex-launcher-flatpak/commit/dd8393c145fdf4994dc16a4740436ac8625251e4 should solve the DXVK issue for the Steam Deck without making anyone manually set exports.

I'm trying out building this GE Proton Wine in the Flatpak at https://github.com/gloriouseggroll/proton-wine/tree/Proton8-24 to see if it works and might fix some of the keyboard issues mentioned.


> ```
> 01cc:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 5, 005F2620, 16): stub
> 01cc:fixme:process:validate_proc_thread_attribute Unhandled attribute 26
> 01cc:fixme:process:CreateProcessInternalW Unsupported attribute 0x2000e.
> 01cc:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenAppContainerSid, ...) semi-stub
> [1128/173244.985:FATAL:gpu_data_manager_impl_private.cc(451)] GPU process isn't usable. Goodbye.
> wine: Unhandled exception 0x80000003 in thread 17c at address 75897EAD (thread 017c), starting debugger...
> Can't attach process 0178: error 5
> ```

That looks like the same issue I had with the GPU that had me chasing `--no-gpu-sandbox` and `--no-sandbox`. I think the issue is intermittent, if you run it multiple times it should just kinda works at some point. Hoping Proton GE or my newly-not-missing configure flags affect this

**Comment by nmlynch94** [comment]
Wine does not support wayland directly right now, at least not well. Recent patch notes have just starting breaking into wayland support from what I've seen, so xwayland is required as far as I'm aware. Even then, I've still seen people have a lot of problems with this project in wayland.

**Comment by nmlynch94** [comment]
Also, might it be worth just using the prebuilt binary for Lutris? I know flatpak encourages building from source, but it's not like we need any specific optimizations or to support multiple architectures for this use-case.

**Comment by USA-RedDragon** [comment]
> Also, might it be worth just using the prebuilt binary for wine-ge?

I _really_ wanted to avoid that, but the build I attempted of it built from source acted bizarrely and I don't feel like trying to debug that :joy:. If the experience is more consistent and less problems occur with the prebuilt, I suppose I can deal with it :shrug: 

Flatpak repo is updating now with the Wine-GE runtime in use

**Comment by TormStorm** [comment]
I tried installing it again and i don't seem to get the Wayland error anymore, but I'm still getting some different errors which makes it crash... [log.txt](https://github.com/TormStorm/jagex-launcher-linux/files/13517004/log.txt)

**Comment by nmlynch94** [comment]
Are these args not to disable sandboxing in CEF? https://github.com/USA-RedDragon/jagex-launcher-flatpak/blob/main/com.jagex.Launcher.yaml#L175

**Comment by USA-RedDragon** [comment]
> Are these args not to disable sandboxing in CEF? https://github.com/USA-RedDragon/jagex-launcher-flatpak/blob/main/resources/com.jagex.Launcher.desktop#L8

:facepalm: Thanks. I was checking the wrong file, thinking I added those in `finish-args`. Remove those and the build is going

---

@TormStorm does this change the behavior at all?

```
flatpak install --user org.freedesktop.Platform.GL.mesa-git org.freedesktop.Platform.GL32.mesa-git
FLATPAK_GL_DRIVERS=mesa-git flatpak run --user com.jagex.Launcher
```

**Comment by nmlynch94** [comment]
No worries! I have an intel graphics machine I can test on when I get home as well to see if I can reproduce.

**Comment by TormStorm** [comment]
Doesn't look like it could find it..
`[torm@torm-pc2 ~]$ flatpak install --user org.freedesktop.Platform.GL.mesa-git org.freedesktop.Platform.GL32.mesa-git
FLATPAK_GL_DRIVERS=mesa-git
Looking for matches…
error: No remote refs found for ‘org.freedesktop.Platform.GL.mesa-git’`

**Comment by USA-RedDragon** [comment]
Ah I see. Looks like those are in flathub-beta.

```
flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo

flatpak install --user flathub-beta org.freedesktop.Platform.GL.mesa-git/x86_64/23.08 org.freedesktop.Platform.GL32.mesa-git/x86_64/23.08

FLATPAK_GL_DRIVERS=mesa-git flatpak run --user com.jagex.Launcher
```

**Comment by USA-RedDragon** [comment]
Well I made a live USB of Nobara Linux 38 and ran it on my 10th gen Intel laptop. Can confirm and reproduce the GPU issue. 

Of course `--no-sandbox` works around this, but I'm not seeing what could make Intel GPUs act out here

**Comment by TormStorm** [comment]
Still seem to get the same error...  [log.txt](https://github.com/TormStorm/jagex-launcher-linux/files/13518121/log.txt)

**Comment by nmlynch94** [comment]
So I'm able to reproduce, and for some reason adding `--allow=devel` back to finish args fixes it. I remember hitting this problem now when I was building mine and tried to use the minimal finish args, and i wasn't able to figure out why this fixed it. Lutris does the same thing so they must have the same or similar issue. 

Didn't have time to test on all devices, but it's working on intel graphics now.

**Comment by USA-RedDragon** [comment]
> for some reason adding --allow=devel back to finish args fixes it

Hmm.. that leads me to think there's some library missing.

> Lutris and bottles do the same thing so they must have the same or similar issue.

If that's the case, I can add it too. It sounds like it'd potentially be a rabbit hole to try to fix.

**Comment by Adamcake** [comment]
Check what happens with the Intel issue if you run with --in-process-gpu?
That makes the GPU sandbox run in a main process thread instead of its own
process. Hopefully it will give more helpful error output instead of just
the generic "subprocess didn't work" message.

**Comment by USA-RedDragon** [comment]
I did attempt that while I was testing different things on my iGPU laptop and iirc it did result in the same error message. Or maybe, (because one of the things I tried definitely did this, but I didn't note down which did what), I got a black window for the launcher that wasn't rendered

**Comment by nmlynch94** [comment]
Sooo had a quick chunk of time to test and good news is that it runs on my intel machine and steam deck now....bad news is it no longer runs on my nvidia machine. I'm not sure if it's a problem with my system or not, but my flatpak still works so I think something is missing. It just hangs until wineboot times out. Does it work on yours? Won't have time to look any closer for awhile.

```
0024:err:environ:run_wineboot boot event wait timed out
wine: could not load kernel32.dll, status c0000135
grep: /var/data/wine/drive_c/user.reg: No such file or directory
00b8:err:environ:run_wineboot boot event wait timed out
wine: could not load kernel32.dll, status c0000135
grep: /var/data/wine/drive_c/user.reg: No such file or directory
```

**Comment by USA-RedDragon** [comment]
Hmm it still works on my system.

Does this change the behavior for you by chance? `WINEDLLOVERRIDES="winegstreamer="` 

If that doesn't, can you try deleting the wineprefix from `~/.var/app/com.jagex.Launcher/data/wine/` and see if the behavior is consistent? I did some digging on that and it seems like that error can occur for a lot of reasons. 

> Won't have time to look any closer today most likely.

Not a problem!

**Comment by nmlynch94** [comment]
Yeah I tested already with deleting the data dir unfortunately with no dice. The dll override didn't fix it either.

I tested the same version of wine-ge in my flatpak and wineboot works somehow just fine. I'm comparing them and am not sure what the cause could be, though. 

Going to do some testing later. Wondering if maybe the runtime has something to do with it. Both bottles and lutris use org.gnome.Platform. Not sure if there is a reason for that.

**Comment by USA-RedDragon** [comment]
This is the diff of all commits in the last couple days since it was working: https://github.com/USA-RedDragon/jagex-launcher-flatpak/compare/d93aa72abe8e015cdc3c3caf0a81fb078f0f8a3a..main. The fact that one (or more) of these changes made your system go from known-working to non-working sort of excludes the possibility that the runtime was bad or that the Gnome runtime is needed.

I theorize that the `--allow=devel` argument swapping from the runtime to the SDK caused this, but no clue as to why. Would you humor me and build it without the `--allow=devel` option just to see if it starts working again on your hardware?

**Comment by nmlynch94** [comment]
Yep looks like it was those prime env vars. Do you by chance have integrated graphics? I do not, so I'm thinking the prime offload var is trying to select the GPU in the next slot which is usually the discrete GPU, but in my case it isn't. Could explain why it's working on yours but not mine. 

I don't think these env vars will handle AMD users with integrated graphics will it? They usually need DRI_PRIME=1. There will likely need to be script logic to handle these properly based on what Lutris is doing. 

Either way, I don't think there is a catchall set of env vars you can set to safely select the discrete GPU on all systems. Looking at Lutris and Bottles, they both have logic around selecting those env vars based on the system.

**Comment by TormStorm** [comment]
Tested it on my laptop now and everything seems to work.

**Pull request merged**
