### PR TITLE
Remove need for JagexLauncherInstaller

### PR DESCRIPTION
**Pull request by nmlynch94**
The Jagex Launcher installer has caused a lot of problems for this setup script. The installation technology is uses seems to have a race condition in Wine where the UI will not properly show, causing an error "Timeout waiting for window to load". 

This PR addresses that by pulling down the installation files using a python script instead. Here are the steps it takes:

1. Pull down the JWT in the Jagex CDN
2. Validate the JWT signature
3. Validate the certificate chain in the header of the JWT
4. Check the fingerprint of the certificate of the signed JWT to make sure it belong to Jagex
5. Download the file fragments, checking their hashes against the digests list as we go
6. Remove proprietary header data from each fragment
7. extract, and combine the files
8. Use the byte sizes for each file listed in the JWT to carve out the files
9. Clean up file fragments

I also removed the explicitly defined wine version. The installer itself only runs in wine-ge, but the JagexLauncher runs completely fine on wine-staging, so it's less important now and will be easier to keep up-to-date this way,

I'm opening this PR to hopefully get some people to test on their system and give feedback. I've tested on both my desktop and my steam deck and confirmed this works in both of those places.

Addresses #11

### CODE REVIEW

**Comment by TormStorm** [comment]
Tested it on my laptop (Kubuntu 23.04) and it worked. This addresses #70 to, right?

**Comment by nmlynch94** [comment]
In theory, if it behaves the way I think it will.

**Comment by TormStorm** [comment]
Would it be possible to open the EULA page from the Lutris script?

**Comment by nmlynch94** [comment]
@TormStorm Done and ready to test.

**Comment by TormStorm** [comment]
Nice, was also thinking if it would be better to have the EULA in the installer itself, but that might just be clunky. Maybe it would be better if you had to press a button instead of the drop-down menu? it seem a bit buggy, at least for me. Not sure if it would be possible to add a checkbox that you would have to tick, although i don't think it would be that important. The text could say something along the line of "By continuing the installation you accept the Jagex EULA"

**Comment by nmlynch94** [comment]
Lutris doesn’t have any option to add check boxes or anything like that, only drop downs. It also doesn’t let you cleanly decide to end the installation based on a drop-down, so I had to use a script. When you exit it just logs that you must accept the Eula. What part was seeming buggy?

**Comment by TormStorm** [comment]
I mean it works, and it displays correctly after scrolling it up and down, it's just a bit janky. Would it maybe be better to have a button, and by pressing that you accept the EULA?
image

**Comment by TormStorm** [comment]
Now that I think about it it doesn’t make sense to add a button since you have to click continue in Lutris. Maybe it should just open the EULA page and say something along the line of “By continuing the installation you accept the EULA”

**Comment by nmlynch94** [comment]
Ah, ok gotcha. Unfortunately, Lutris doesn’t let you add buttons. Only drop-down menus.

**Pull request merged**
