### PR TITLE
Use SSL to validate downloads

### LINKED ISSUE #126: Metafile isn't always a JWT
Related #125

The metafile that `launcher-win.production` refers to doesn't always seem to be a JWT. If you run this currently, it'll grab 

image

The file: http://jagex-akamai.aws.snxd.com/direct6/launcher-win/metafile/cc5e6fbd2073cf82e360e83127ffb076450e34b44a2dc3bda203b8e760c15a7e/metafile.json is the metadata it grabs

And the error
```
Latest metafile_url: http://jagex-akamai.aws.snxd.com/direct6/launcher-win/metafile/cc5e6fbd2073cf82e360e83127ffb076450e34b44a2dc3bda203b8e760c15a7e/metafile.json
  File "/tmp/tmp.pb87XpSy3D/jagex-launcher-linux/resources/installer.py", line 200, in <module>
    main()
  File "/tmp/tmp.pb87XpSy3D/jagex-launcher-linux/resources/installer.py", line 112, in main
    jwt = jwcrypto.jwt.JWT(jwt=jwt.decode("ascii"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.pb87XpSy3D/jagex-launcher-linux/venv/lib/python3.12/site-packages/jwcrypto/jwt.py", line 231, in __init__
    self.deserialize(jwt, key)
  File "/tmp/tmp.pb87XpSy3D/jagex-launcher-linux/venv/lib/python3.12/site-packages/jwcrypto/jwt.py", line 670, in deserialize
    raise ValueError("Token format unrecognized")
ValueError: Token format unrecognized
```

### PR DESCRIPTION
**Pull request by USA-RedDragon**
Fixes #126

Jagex seems to not be shipping a JWT with their latest release. This change swaps the code to use the proper hostname and lets `requests` validate the CA certificate chain. This removes all dependencies. SSL certificates that do not validate still get the following exception:

```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'jagex-akamai.aws.snxd.com'. (_ssl.c:1007)>
```

I also removed unused imports and added a fix for a potential extra error message by importing `binascii`

### CODE REVIEW

**Comment by nmlynch94** [comment]
I’m Looks good to me. Very happy we can remove all that cert validation code. I can test this in about an hour.

**Comment by nmlynch94** [comment]
@TormStorm Confirmed this is working properly

**Comment by TormStorm** [comment]
> @TormStorm Confirmed this is working properly

With all the dependencies removed as well?

**Comment by nmlynch94** [comment]
Yep. I used a clean virtual environment to run it.

**Pull request merged**
